/** App Store storefronts used for price comparison. */
export const STOREFRONTS = [
  { code: 'us', name: '美国', currency: 'USD', flag: '🇺🇸' },
  { code: 'tr', name: '土耳其', currency: 'TRY', flag: '🇹🇷' },
  { code: 'ph', name: '菲律宾', currency: 'PHP', flag: '🇵🇭' },
  { code: 'in', name: '印度', currency: 'INR', flag: '🇮🇳' },
  { code: 'pk', name: '巴基斯坦', currency: 'PKR', flag: '🇵🇰' },
  { code: 'ng', name: '尼日利亚', currency: 'NGN', flag: '🇳🇬' },
  { code: 'eg', name: '埃及', currency: 'EGP', flag: '🇪🇬' },
  { code: 'za', name: '南非', currency: 'ZAR', flag: '🇿🇦' },
  { code: 'br', name: '巴西', currency: 'BRL', flag: '🇧🇷' },
  { code: 'mx', name: '墨西哥', currency: 'MXN', flag: '🇲🇽' },
  { code: 'ar', name: '阿根廷', currency: 'ARS', flag: '🇦🇷' },
  { code: 'cl', name: '智利', currency: 'CLP', flag: '🇨🇱' },
  { code: 'co', name: '哥伦比亚', currency: 'COP', flag: '🇨🇴' },
  { code: 'pe', name: '秘鲁', currency: 'PEN', flag: '🇵🇪' },
  { code: 'ca', name: '加拿大', currency: 'CAD', flag: '🇨🇦' },
  { code: 'gb', name: '英国', currency: 'GBP', flag: '🇬🇧' },
  { code: 'ie', name: '爱尔兰', currency: 'EUR', flag: '🇮🇪' },
  { code: 'de', name: '德国', currency: 'EUR', flag: '🇩🇪' },
  { code: 'fr', name: '法国', currency: 'EUR', flag: '🇫🇷' },
  { code: 'it', name: '意大利', currency: 'EUR', flag: '🇮🇹' },
  { code: 'es', name: '西班牙', currency: 'EUR', flag: '🇪🇸' },
  { code: 'nl', name: '荷兰', currency: 'EUR', flag: '🇳🇱' },
  { code: 'pl', name: '波兰', currency: 'PLN', flag: '🇵🇱' },
  { code: 'se', name: '瑞典', currency: 'SEK', flag: '🇸🇪' },
  { code: 'no', name: '挪威', currency: 'NOK', flag: '🇳🇴' },
  { code: 'ch', name: '瑞士', currency: 'CHF', flag: '🇨🇭' },
  { code: 'ru', name: '俄罗斯', currency: 'RUB', flag: '🇷🇺' },
  { code: 'ua', name: '乌克兰', currency: 'UAH', flag: '🇺🇦' },
  { code: 'jp', name: '日本', currency: 'JPY', flag: '🇯🇵' },
  { code: 'kr', name: '韩国', currency: 'KRW', flag: '🇰🇷' },
  { code: 'tw', name: '台湾', currency: 'TWD', flag: '🇹🇼' },
  { code: 'hk', name: '香港', currency: 'HKD', flag: '🇭🇰' },
  { code: 'sg', name: '新加坡', currency: 'SGD', flag: '🇸🇬' },
  { code: 'my', name: '马来西亚', currency: 'MYR', flag: '🇲🇾' },
  { code: 'th', name: '泰国', currency: 'THB', flag: '🇹🇭' },
  { code: 'id', name: '印尼', currency: 'IDR', flag: '🇮🇩' },
  { code: 'vn', name: '越南', currency: 'VND', flag: '🇻🇳' },
  { code: 'au', name: '澳大利亚', currency: 'AUD', flag: '🇦🇺' },
  { code: 'nz', name: '新西兰', currency: 'NZD', flag: '🇳🇿' },
  { code: 'ae', name: '阿联酋', currency: 'AED', flag: '🇦🇪' },
  { code: 'sa', name: '沙特', currency: 'SAR', flag: '🇸🇦' },
  { code: 'il', name: '以色列', currency: 'ILS', flag: '🇮🇱' },
  { code: 'cn', name: '中国大陆', currency: 'CNY', flag: '🇨🇳' },
]

export const STOREFRONT_MAP = Object.fromEntries(STOREFRONTS.map((s) => [s.code, s]))
