import type { Locale } from './index'

/** v5: 13 new lab mascots (names, moves, intro, win) + picker / in-canvas UI strings, 12 locales. */
export const NEW_AVATARS = ['meta', 'mistral', 'bytedance', 'tencent', 'nvidia', 'minimax', 'amazon', 'microsoft', 'cohere', 'stepfun', 'baidu', 'xiaomi', 'mystery'] as const
type NA = (typeof NEW_AVATARS)[number]
type Pack = { chars: string[]; moves: string[]; intro: string[]; win: string[] }
export type V5Ui = {
  vendor: string; model: string; search: string; sort: string; sortComp: string; sortName: string; sortNew: string
  boardsN: string; fewData: string; newcomer: string; comp: string; noCommon: string; loading: string; models: string
  super: string; parry: string; block: string; crit: string; counter: string; guardBreak: string; finish: string; winner: string; round: string
  other: string; openFull: string; live: string; boards: Record<string, string>
}

const P: Record<string, Pack> = {
  'zh-CN': {
    chars: ['Meta 无限环', 'Mistral 疾风 M', '豆包 包子侠', '混元企鹅', 'NVIDIA 绿瞳芯', 'MiniMax 波形怪', 'Amazon 包裹侠', 'Microsoft 四色方块', 'Cohere 珊瑚团子', '阶跃君', '文心熊掌宝', '米兔', '神秘挑战者'],
    moves: ['无限回环·元宇宙陀螺斩！', '西北疾风·像素 M 旋风！', '豆包·热气腾腾蒸笼炮！', '混元·冰原企鹅滑铲！', '绿瞳·算力过载雷霆！', '声波·满格音浪冲击！', '次日达·包裹火箭炮！', '四色·蓝屏结界！', '珊瑚·三连团子弹！', '阶跃·登天三段跳！', '熊掌·文心一掌！', '米兔·性价比飞踢！', '？？？·未知之刃！'],
    intro: ['无限循环开始，你逃不出这个环！', '风从巴黎吹来，带着开源的味道！', '刚出锅的，小心烫手！', '嘎！先发个红包再开打。', '显卡已就位，帧数拉满！', '听好了，这是你最后一首歌。', '预计送达：你的败北。', '别担心，我会自动更新到赢。', '我们三个一起上，算一个人哦！', '一步一个台阶，一脚踩到你头上！', '熊掌一出，谁与争锋？', '为发烧而生，为胜利而跳！', '我是谁？赢了再告诉你。'],
    win: ['循环结束……又从头开始了？（转晕）', '风停了，发型还在吗？', '胜利出锅！（自己被烫到）', '嘎嘎！今晚吃鱼！（滑倒）', '胜利已渲染完毕。（风扇狂转）', '安可！安可！……没人鼓掌吗？', '已签收！（被纸箱卡住）', '胜利！……正在重启，请勿关机。', '团子三兄弟，永远不分开！（撞成一团）', '登顶！……下楼怎么走？', '熊掌赢了，蜂蜜归我！', '赢了，而且价格感人！（耳朵打结）', '身份……还是保密吧。（兜帽掉了）'],
  },
  'zh-TW': {
    chars: ['Meta 無限環', 'Mistral 疾風 M', '豆包 包子俠', '混元企鵝', 'NVIDIA 綠瞳芯', 'MiniMax 波形怪', 'Amazon 包裹俠', 'Microsoft 四色方塊', 'Cohere 珊瑚糰子', '階躍君', '文心熊掌寶', '米兔', '神秘挑戰者'],
    moves: ['無限迴環·元宇宙陀螺斬！', '西北疾風·像素 M 旋風！', '豆包·熱氣騰騰蒸籠砲！', '混元·冰原企鵝滑鏟！', '綠瞳·算力過載雷霆！', '聲波·滿格音浪衝擊！', '隔日達·包裹火箭砲！', '四色·藍屏結界！', '珊瑚·三連糰子彈！', '階躍·登天三段跳！', '熊掌·文心一掌！', '米兔·CP 值飛踢！', '？？？·未知之刃！'],
    intro: ['無限循環開始，你逃不出這個環！', '風從巴黎吹來，帶著開源的味道！', '剛出爐的，小心燙手！', '嘎！先發個紅包再開打。', '顯卡已就位，幀數拉滿！', '聽好了，這是你最後一首歌。', '預計送達：你的敗北。', '別擔心，我會自動更新到贏。', '我們三個一起上，算一個人喔！', '一步一個台階，一腳踩到你頭上！', '熊掌一出，誰與爭鋒？', '為發燒而生，為勝利而跳！', '我是誰？贏了再告訴你。'],
    win: ['循環結束……又從頭開始了？（轉暈）', '風停了，髮型還在嗎？', '勝利出爐！（自己被燙到）', '嘎嘎！今晚吃魚！（滑倒）', '勝利已算繪完畢。（風扇狂轉）', '安可！安可！……沒人鼓掌嗎？', '已簽收！（被紙箱卡住）', '勝利！……正在重新啟動，請勿關機。', '糰子三兄弟，永遠不分開！（撞成一團）', '登頂！……下樓怎麼走？', '熊掌贏了，蜂蜜歸我！', '贏了，而且價格感人！（耳朵打結）', '身分……還是保密吧。（兜帽掉了）'],
  },
  en: {
    chars: ['Meta Infinity Loop', 'Mistral Gale M', 'Doubao Bun Hero', 'Hunyuan Penguin', 'NVIDIA Green-Eye Chip', 'MiniMax Waveform', 'Amazon Parcel Hero', 'Microsoft Four Squares', 'Cohere Coral Dumplings', 'StepFun Stairs', 'ERNIE Bear Paw', 'Xiaomi Mitu Bunny', 'Mystery Challenger'],
    moves: ['Infinite Loop: Metaverse Spin Slash!', 'Mistral Gale: Pixel-M Cyclone!', 'Doubao: Steaming Bun Cannon!', 'Hunyuan: Ice-Floe Penguin Slide!', 'Green Eye: Compute Overload Thunder!', 'Soundwave: Full-Bar Sonic Blast!', 'Next-Day: Parcel Rocket!', 'Four Squares: Blue-Screen Barrier!', 'Coral: Triple Dumpling Shot!', 'StepFun: Sky-Stair Triple Jump!', 'Bear Paw: ERNIE Palm Strike!', 'Mitu: Best-Value Flying Kick!', '???: Blade of the Unknown!'],
    intro: ['The infinite loop begins. You can’t escape!', 'A wind from Paris, smelling of open weights!', 'Fresh out of the steamer. Careful, it’s hot!', 'Squawk! Red envelope first, then we fight.', 'GPUs ready. Frame rate maxed!', 'Listen well. This is your last song.', 'Estimated delivery: your defeat.', 'Don’t worry, I’ll auto-update until I win.', 'All three of us count as one fighter, okay?', 'One step at a time… right onto your head!', 'When the paw comes out, who can stand?', 'Born for fans, jumping for victory!', 'Who am I? I’ll tell you after I win.'],
    win: ['Loop complete… wait, it restarted? (dizzy)', 'The wind stopped. Is my hair okay?', 'Victory, served hot! (burns self)', 'Squawk! Fish tonight! (slips)', 'Victory rendered. (fans screaming)', 'Encore! Encore! …anyone clapping?', 'Delivered! (stuck in the box)', 'Victory! …restarting, do not power off.', 'Dumpling trio, together forever! (bonk)', 'Summit! …how do I get down?', 'The paw wins. The honey is mine!', 'Won, and at a great price! (ears tangled)', 'My identity… stays secret. (hood falls off)'],
  },
  ja: {
    chars: ['Meta インフィニティ', 'Mistral 疾風M', 'Doubao 肉まんヒーロー', '混元ペンギン', 'NVIDIA 緑眼チップ', 'MiniMax 波形くん', 'Amazon 段ボール侠', 'Microsoft 四色ブロック', 'Cohere サンゴ団子', 'StepFun 階段くん', 'ERNIE クマの手', 'Xiaomi ミートゥ', '謎の挑戦者'],
    moves: ['無限ループ・メタバース回転斬！', '疾風・ピクセルMサイクロン！', '肉まん・ほかほか蒸籠砲！', '混元・氷原ペンギンスライド！', '緑眼・演算オーバーロード雷撃！', '音波・フルゲージ衝撃波！', '翌日配達・小包ロケット！', '四色・ブルースクリーン結界！', 'サンゴ・三連団子弾！', '階段・天まで三段跳び！', 'クマの手・文心掌底！', 'ミートゥ・コスパ飛び蹴り！', '？？？・未知の刃！'],
    intro: ['無限ループ開始。この輪からは逃げられない！', 'パリからの風、オープンウェイトの香り！', '蒸したてだよ、やけどに注意！', 'ガー！まずはお年玉、それから勝負。', 'GPU準備完了、フレームレート全開！', 'よく聞け、これが最後の一曲だ。', 'お届け予定：あなたの敗北。', '心配無用、勝つまで自動更新します。', '三人まとめて一人扱いでよろしく！', '一歩ずつ…君の頭の上まで！', 'クマの手が出たら、誰が止める？', 'ファンのために生まれ、勝利へ跳ぶ！', '正体？勝ったら教えてあげる。'],
    win: ['ループ終了…あれ、また最初から？（目が回る）', '風が止んだ。髪型、大丈夫？', '勝利、蒸し上がり！（自分でやけど）', 'ガーガー！今夜は魚だ！（すべる）', '勝利のレンダリング完了。（ファン全開）', 'アンコール！…拍手は？', 'お届け完了！（箱にはまる）', '勝利！…再起動中、電源を切らないで。', '団子三兄弟、ずっと一緒！（ごっつん）', '登頂！…降り方は？', 'クマの勝ち。ハチミツはいただき！', '勝った、しかもお買い得！（耳が絡まる）', '正体は…ナイショ。（フードが落ちる）'],
  },
  ko: {
    chars: ['Meta 무한 루프', 'Mistral 질풍 M', 'Doubao 찐빵 히어로', '훈위안 펭귄', 'NVIDIA 녹안 칩', 'MiniMax 파형이', 'Amazon 택배 히어로', 'Microsoft 네 색 블록', 'Cohere 산호 경단', 'StepFun 계단군', 'ERNIE 곰발바닥', 'Xiaomi 미투 토끼', '수수께끼 도전자'],
    moves: ['무한 루프·메타버스 회전 베기!', '질풍·픽셀 M 사이클론!', '찐빵·모락모락 찜통포!', '훈위안·빙원 펭귄 슬라이딩!', '녹안·연산 과부하 천둥!', '음파·풀게이지 충격파!', '익일배송·택배 로켓!', '네 색·블루스크린 결계!', '산호·삼연 경단탄!', '계단·하늘 삼단 뛰기!', '곰발바닥·문심 장타!', '미투·가성비 플라잉킥!', '???·미지의 칼날!'],
    intro: ['무한 루프 시작. 이 고리에선 못 빠져나가!', '파리에서 불어온 바람, 오픈 웨이트 향기!', '갓 쪄냈어, 뜨거우니 조심!', '꽥! 세뱃돈부터 주고 싸우자.', 'GPU 준비 완료, 프레임 최대!', '잘 들어, 이게 네 마지막 노래야.', '도착 예정: 너의 패배.', '걱정 마, 이길 때까지 자동 업데이트.', '우리 셋이 한 명으로 칠게!', '한 계단씩… 네 머리 위까지!', '곰발바닥이 나오면 누가 막아?', '팬을 위해 태어나, 승리를 향해 점프!', '내가 누구냐고? 이기면 알려 줄게.'],
    win: ['루프 끝… 어, 처음부터 다시? (어질)', '바람이 멎었다. 머리 괜찮아?', '승리, 따끈하게 완성! (스스로 데임)', '꽥꽥! 오늘 밤은 생선! (미끄덩)', '승리 렌더링 완료. (팬 굉음)', '앙코르! …박수 없나?', '배송 완료! (상자에 끼임)', '승리! …재시작 중, 전원을 끄지 마세요.', '경단 삼형제, 영원히 함께! (쿵)', '정상 도착! …내려가는 법은?', '곰발바닥 승리. 꿀은 내 거!', '이겼다, 게다가 가성비까지! (귀 엉킴)', '정체는… 비밀. (후드가 벗겨짐)'],
  },
  fr: {
    chars: ['Meta Boucle Infinie', 'Mistral M Rafale', 'Doubao Héros Brioche', 'Pingouin Hunyuan', 'NVIDIA Puce Œil-Vert', 'MiniMax Forme d’Onde', 'Amazon Héros Colis', 'Microsoft Quatre Carrés', 'Cohere Boulettes Corail', 'StepFun Escalier', 'ERNIE Patte d’Ours', 'Xiaomi Lapin Mitu', 'Challenger Mystère'],
    moves: ['Boucle infinie : taille métavers !', 'Rafale : cyclone pixel-M !', 'Doubao : canon à brioches fumantes !', 'Hunyuan : glissade de pingouin !', 'Œil vert : foudre de surcharge !', 'Onde : souffle sonore plein !', 'Livraison J+1 : roquette colis !', 'Quatre carrés : barrière écran bleu !', 'Corail : triple tir de boulettes !', 'StepFun : triple saut céleste !', 'Patte d’ours : paume ERNIE !', 'Mitu : coup de pied rapport qualité-prix !', '??? : lame de l’inconnu !'],
    intro: ['La boucle infinie commence. Pas d’échappatoire !', 'Un vent de Paris, parfum de poids ouverts !', 'Tout juste sorti du panier vapeur, attention !', 'Coin ! L’enveloppe rouge d’abord, puis on se bat.', 'GPU prêts. Images par seconde au max !', 'Écoute bien : c’est ta dernière chanson.', 'Livraison estimée : ta défaite.', 'Pas d’inquiétude, je me mets à jour jusqu’à gagner.', 'À nous trois, on compte pour un, d’accord ?', 'Marche après marche… jusque sur ta tête !', 'Quand la patte sort, qui résiste ?', 'Né pour les fans, je saute vers la victoire !', 'Qui je suis ? Je te le dirai après avoir gagné.'],
    win: ['Boucle finie… elle recommence ? (tournis)', 'Le vent est tombé. Ma coiffure tient ?', 'Victoire servie chaude ! (se brûle)', 'Coin coin ! Poisson ce soir ! (glisse)', 'Victoire rendue. (ventilos à fond)', 'Bis ! Bis ! …personne n’applaudit ?', 'Livré ! (coincé dans le carton)', 'Victoire ! …redémarrage, ne pas éteindre.', 'Trio de boulettes pour toujours ! (bonk)', 'Sommet ! …on descend comment ?', 'La patte gagne. Le miel est à moi !', 'Gagné, et pas cher ! (oreilles nouées)', 'Mon identité… reste secrète. (capuche tombée)'],
  },
  de: {
    chars: ['Meta Endlosschleife', 'Mistral Sturm-M', 'Doubao Dampfnudel-Held', 'Hunyuan-Pinguin', 'NVIDIA Grünaugen-Chip', 'MiniMax Wellenform', 'Amazon Paket-Held', 'Microsoft Vier Quadrate', 'Cohere Korallenknödel', 'StepFun Treppe', 'ERNIE Bärentatze', 'Xiaomi Mitu-Hase', 'Mysteriöser Herausforderer'],
    moves: ['Endlosschleife: Metaverse-Wirbelhieb!', 'Sturm: Pixel-M-Zyklon!', 'Doubao: Dampfende Knödelkanone!', 'Hunyuan: Eisschollen-Pinguinrutsche!', 'Grünauge: Rechenlast-Donner!', 'Schallwelle: Vollpegel-Druckwelle!', 'Morgen da: Paketrakete!', 'Vier Quadrate: Bluescreen-Barriere!', 'Koralle: Dreifach-Knödelschuss!', 'StepFun: Himmelstreppen-Dreisprung!', 'Bärentatze: ERNIE-Handflächenschlag!', 'Mitu: Preis-Leistungs-Flugtritt!', '???: Klinge des Unbekannten!'],
    intro: ['Die Endlosschleife beginnt. Kein Entkommen!', 'Ein Wind aus Paris, mit Duft offener Gewichte!', 'Frisch aus dem Dampfkorb – Vorsicht, heiß!', 'Quak! Erst der rote Umschlag, dann der Kampf.', 'GPUs bereit. Bildrate am Anschlag!', 'Hör gut zu: Das ist dein letztes Lied.', 'Voraussichtliche Zustellung: deine Niederlage.', 'Keine Sorge, ich update mich, bis ich gewinne.', 'Wir drei zählen als ein Kämpfer, okay?', 'Stufe für Stufe… bis auf deinen Kopf!', 'Wenn die Tatze kommt, wer hält stand?', 'Für Fans geboren, zum Sieg gesprungen!', 'Wer ich bin? Sag ich dir nach dem Sieg.'],
    win: ['Schleife fertig… fängt sie wieder an? (schwindlig)', 'Der Wind ist weg. Sitzt die Frisur?', 'Sieg, heiß serviert! (verbrennt sich)', 'Quak quak! Heute gibt’s Fisch! (rutscht aus)', 'Sieg gerendert. (Lüfter heulen)', 'Zugabe! …klatscht keiner?', 'Zugestellt! (steckt im Karton)', 'Sieg! …Neustart, bitte nicht ausschalten.', 'Knödel-Trio für immer! (bonk)', 'Gipfel! …wie komm ich runter?', 'Die Tatze siegt. Der Honig gehört mir!', 'Gewonnen, und günstig! (Ohren verknotet)', 'Meine Identität… bleibt geheim. (Kapuze fällt)'],
  },
  es: {
    chars: ['Meta Bucle Infinito', 'Mistral M Ventarrón', 'Doubao Héroe Bollo', 'Pingüino Hunyuan', 'NVIDIA Chip Ojo Verde', 'MiniMax Forma de Onda', 'Amazon Héroe Paquete', 'Microsoft Cuatro Cuadros', 'Cohere Bolitas de Coral', 'StepFun Escalera', 'ERNIE Pata de Oso', 'Xiaomi Conejo Mitu', 'Retador Misterioso'],
    moves: ['Bucle infinito: ¡tajo metaverso!', 'Ventarrón: ¡ciclón pixel-M!', 'Doubao: ¡cañón de bollos humeantes!', 'Hunyuan: ¡deslizón de pingüino!', 'Ojo verde: ¡trueno de sobrecarga!', 'Onda: ¡explosión sónica a tope!', 'Entrega exprés: ¡cohete paquete!', 'Cuatro cuadros: ¡barrera pantallazo azul!', 'Coral: ¡triple disparo de bolitas!', 'StepFun: ¡triple salto al cielo!', 'Pata de oso: ¡palmazo ERNIE!', 'Mitu: ¡patada voladora calidad-precio!', '???: ¡hoja de lo desconocido!'],
    intro: ['Empieza el bucle infinito. ¡No hay escape!', '¡Un viento de París con aroma a pesos abiertos!', 'Recién salido de la vaporera, ¡quema!', '¡Cuac! Primero el sobre rojo, luego peleamos.', 'GPU listas. ¡Fotogramas al máximo!', 'Escucha bien: esta es tu última canción.', 'Entrega estimada: tu derrota.', 'Tranquilo, me actualizo hasta ganar.', 'Los tres contamos como uno, ¿vale?', 'Paso a paso… ¡hasta tu cabeza!', 'Cuando sale la pata, ¿quién aguanta?', '¡Nacido para los fans, salto a la victoria!', '¿Quién soy? Te lo digo cuando gane.'],
    win: ['Bucle terminado… ¿empieza otra vez? (mareo)', 'Paró el viento. ¿Sigue mi peinado?', '¡Victoria recién hecha! (se quema)', '¡Cuac cuac! ¡Pescado esta noche! (resbala)', 'Victoria renderizada. (ventiladores a tope)', '¡Otra! ¡Otra! …¿nadie aplaude?', '¡Entregado! (atascado en la caja)', '¡Victoria! …reiniciando, no apagues.', '¡Trío de bolitas para siempre! (bonk)', '¡Cima! …¿cómo bajo?', 'Gana la pata. ¡La miel es mía!', '¡Gané, y a buen precio! (orejas enredadas)', 'Mi identidad… es secreta. (se cae la capucha)'],
  },
  hi: {
    chars: ['Meta अनंत लूप', 'Mistral तूफ़ानी M', 'Doubao बन हीरो', 'हुनयुआन पेंगुइन', 'NVIDIA हरी-आँख चिप', 'MiniMax वेवफ़ॉर्म', 'Amazon पार्सल हीरो', 'Microsoft चार चौकोर', 'Cohere कोरल गोले', 'StepFun सीढ़ी', 'ERNIE भालू पंजा', 'Xiaomi मीतू खरगोश', 'रहस्यमय चैलेंजर'],
    moves: ['अनंत लूप: मेटावर्स घूमता वार!', 'तूफ़ान: पिक्सेल-M चक्रवात!', 'Doubao: भाप वाला बन तोप!', 'हुनयुआन: बर्फ़ीली पेंगुइन स्लाइड!', 'हरी आँख: कंप्यूट ओवरलोड बिजली!', 'ध्वनि तरंग: फुल-बार धमाका!', 'अगले दिन डिलीवरी: पार्सल रॉकेट!', 'चार चौकोर: ब्लू-स्क्रीन कवच!', 'कोरल: तिहरा गोला वार!', 'StepFun: आसमानी तिहरी छलांग!', 'भालू पंजा: ERNIE हथेली वार!', 'मीतू: किफ़ायती फ़्लाइंग किक!', '???: अज्ञात की तलवार!'],
    intro: ['अनंत लूप शुरू। तुम बच नहीं सकते!', 'पेरिस से आई हवा, ओपन वेट्स की ख़ुशबू!', 'अभी भाप से निकला है, गरम है!', 'क्वैक! पहले लाल लिफ़ाफ़ा, फिर लड़ाई।', 'GPU तैयार। फ़्रेम रेट फुल!', 'ध्यान से सुनो, यह तुम्हारा आख़िरी गाना है।', 'अनुमानित डिलीवरी: तुम्हारी हार।', 'चिंता मत करो, जीतने तक ऑटो-अपडेट करूँगा।', 'हम तीनों को एक ही गिनना, ठीक?', 'एक-एक सीढ़ी… सीधे तुम्हारे सिर पर!', 'पंजा निकला तो कौन टिकेगा?', 'फ़ैन्स के लिए जन्मा, जीत के लिए उछला!', 'मैं कौन हूँ? जीतने के बाद बताऊँगा।'],
    win: ['लूप पूरा… अरे, फिर से शुरू? (चक्कर)', 'हवा थम गई। बाल ठीक हैं?', 'जीत, गरमागरम! (ख़ुद जल गया)', 'क्वैक! आज रात मछली! (फिसला)', 'जीत रेंडर हो गई। (पंखे चीख़ रहे)', 'वन्स मोर! …कोई ताली?', 'डिलीवर! (डिब्बे में फँसा)', 'जीत! …रीस्टार्ट हो रहा है, बंद न करें।', 'गोला तिकड़ी हमेशा साथ! (टक्कर)', 'चोटी पर! …नीचे कैसे उतरें?', 'पंजा जीता। शहद मेरा!', 'जीत गया, और सस्ते में! (कान उलझे)', 'मेरी पहचान… राज़ ही रहेगी। (हुड गिरा)'],
  },
  th: {
    chars: ['Meta วงอนันต์', 'Mistral M พายุ', 'Doubao ฮีโร่ซาลาเปา', 'เพนกวินฮุนหยวน', 'NVIDIA ชิปตาเขียว', 'MiniMax คลื่นเสียง', 'Amazon ฮีโร่พัสดุ', 'Microsoft สี่ช่อง', 'Cohere ก้อนปะการัง', 'StepFun บันได', 'ERNIE อุ้งเท้าหมี', 'Xiaomi กระต่ายมีทู', 'ผู้ท้าชิงปริศนา'],
    moves: ['วงอนันต์: ฟันหมุนเมตาเวิร์ส!', 'พายุ: ไซโคลนพิกเซล M!', 'Doubao: ปืนใหญ่ซาลาเปาร้อน!', 'ฮุนหยวน: เพนกวินสไลด์น้ำแข็ง!', 'ตาเขียว: สายฟ้าประมวลผลล้น!', 'คลื่นเสียง: ระเบิดเสียงเต็มหลอด!', 'ส่งด่วน: จรวดพัสดุ!', 'สี่ช่อง: บาเรียจอฟ้า!', 'ปะการัง: ยิงก้อนสามลูก!', 'StepFun: กระโดดสามขั้นสู่ฟ้า!', 'อุ้งเท้าหมี: ฝ่ามือ ERNIE!', 'มีทู: ลูกเตะคุ้มค่า!', '???: ใบมีดแห่งความลับ!'],
    intro: ['วงอนันต์เริ่มแล้ว หนีไม่พ้นหรอก!', 'ลมจากปารีส กลิ่นโอเพนเวต!', 'เพิ่งออกจากซึ้ง ระวังร้อน!', 'แคว้ก! ขออั่งเปาก่อนค่อยสู้', 'GPU พร้อม เฟรมเรตเต็มที่!', 'ฟังให้ดี นี่คือเพลงสุดท้ายของเจ้า', 'กำหนดส่ง: ความพ่ายแพ้ของเจ้า', 'ไม่ต้องห่วง จะอัปเดตจนกว่าจะชนะ', 'เราสามคนนับเป็นหนึ่งนะ!', 'ทีละขั้น… ขึ้นไปบนหัวเจ้า!', 'อุ้งเท้าออกมาเมื่อไหร่ ใครจะต้าน?', 'เกิดมาเพื่อแฟนๆ กระโดดสู่ชัยชนะ!', 'ข้าเป็นใคร? ชนะแล้วจะบอก'],
    win: ['วนจบ… เอ๊ะ เริ่มใหม่อีก? (มึน)', 'ลมหยุดแล้ว ทรงผมยังอยู่ไหม?', 'ชัยชนะร้อนๆ! (ลวกตัวเอง)', 'แคว้กๆ! คืนนี้กินปลา! (ลื่น)', 'เรนเดอร์ชัยชนะเสร็จ (พัดลมหมุนติ้ว)', 'อีกเพลง! …ไม่มีใครปรบมือเหรอ?', 'ส่งถึงแล้ว! (ติดในกล่อง)', 'ชนะ! …กำลังรีสตาร์ต ห้ามปิดเครื่อง', 'สามก้อนอยู่ด้วยกันตลอดไป! (ชนกัน)', 'ถึงยอด! …ลงยังไง?', 'อุ้งเท้าชนะ น้ำผึ้งเป็นของข้า!', 'ชนะ แถมราคาดี! (หูพันกัน)', 'ตัวตน… เป็นความลับ (ฮู้ดหลุด)'],
  },
  ru: {
    chars: ['Meta Бесконечная петля', 'Mistral Шквал-M', 'Doubao Герой-баоцзы', 'Пингвин Хуньюань', 'NVIDIA Зеленоглазый чип', 'MiniMax Волна', 'Amazon Герой-посылка', 'Microsoft Четыре квадрата', 'Cohere Коралловые шарики', 'StepFun Лесенка', 'ERNIE Медвежья лапа', 'Xiaomi Кролик Mitu', 'Таинственный претендент'],
    moves: ['Петля: метавселенский вихрь!', 'Шквал: пиксельный M-циклон!', 'Doubao: пушка горячих баоцзы!', 'Хуньюань: пингвиний подкат!', 'Зелёный глаз: гром перегрузки!', 'Звуковая волна: удар на полной шкале!', 'Доставка завтра: ракета-посылка!', 'Четыре квадрата: барьер синего экрана!', 'Коралл: тройной выстрел шариками!', 'StepFun: тройной прыжок в небо!', 'Медвежья лапа: удар ладонью ERNIE!', 'Mitu: выгодный удар в прыжке!', '???: клинок неизвестности!'],
    intro: ['Бесконечная петля началась. Не сбежишь!', 'Ветер из Парижа пахнет открытыми весами!', 'Только из пароварки — горячо!', 'Кря! Сначала красный конверт, потом бой.', 'GPU готовы. Кадры на максимум!', 'Слушай внимательно: это твоя последняя песня.', 'Ожидаемая доставка: твоё поражение.', 'Не волнуйся, обновлюсь до победы.', 'Мы втроём считаемся за одного, ладно?', 'Шаг за шагом… прямо тебе на голову!', 'Когда выходит лапа — кто устоит?', 'Рождён для фанатов, прыгаю к победе!', 'Кто я? Скажу после победы.'],
    win: ['Петля закончилась… опять сначала? (голова кружится)', 'Ветер стих. Причёска цела?', 'Победа с пылу с жару! (обжёгся)', 'Кря-кря! Сегодня рыба! (поскользнулся)', 'Победа отрендерена. (кулеры воют)', 'Бис! Бис! …никто не хлопает?', 'Доставлено! (застрял в коробке)', 'Победа! …перезагрузка, не выключайте.', 'Трио шариков навсегда! (бум)', 'Вершина! …а как спуститься?', 'Лапа победила. Мёд мой!', 'Победа, и недорого! (уши запутались)', 'Кто я… останется тайной. (капюшон упал)'],
  },
  pt: {
    chars: ['Meta Loop Infinito', 'Mistral M Ventania', 'Doubao Herói Bao', 'Pinguim Hunyuan', 'NVIDIA Chip Olho-Verde', 'MiniMax Forma de Onda', 'Amazon Herói Pacote', 'Microsoft Quatro Quadrados', 'Cohere Bolinhas de Coral', 'StepFun Escada', 'ERNIE Pata de Urso', 'Xiaomi Coelho Mitu', 'Desafiante Misterioso'],
    moves: ['Loop infinito: corte metaverso!', 'Ventania: ciclone pixel-M!', 'Doubao: canhão de bao fumegante!', 'Hunyuan: deslize de pinguim!', 'Olho verde: trovão de sobrecarga!', 'Onda: explosão sonora no máximo!', 'Entrega amanhã: foguete-pacote!', 'Quatro quadrados: barreira tela azul!', 'Coral: tiro triplo de bolinhas!', 'StepFun: salto triplo ao céu!', 'Pata de urso: palmada ERNIE!', 'Mitu: voadora custo-benefício!', '???: lâmina do desconhecido!'],
    intro: ['O loop infinito começou. Sem fuga!', 'Um vento de Paris, cheiro de pesos abertos!', 'Saído do vapor agora, cuidado que queima!', 'Quá! Primeiro o envelope vermelho, depois a luta.', 'GPUs prontas. Taxa de quadros no máximo!', 'Ouça bem: esta é sua última canção.', 'Entrega prevista: sua derrota.', 'Relaxa, eu me atualizo até vencer.', 'Nós três contamos como um, beleza?', 'Degrau por degrau… até a sua cabeça!', 'Quando a pata sai, quem aguenta?', 'Nascido para os fãs, saltando para a vitória!', 'Quem sou eu? Conto depois de vencer.'],
    win: ['Loop concluído… começou de novo? (tonto)', 'O vento parou. Meu cabelo está ok?', 'Vitória quentinha! (se queima)', 'Quá quá! Peixe hoje! (escorrega)', 'Vitória renderizada. (ventoinhas gritando)', 'Bis! Bis! …ninguém aplaude?', 'Entregue! (preso na caixa)', 'Vitória! …reiniciando, não desligue.', 'Trio de bolinhas para sempre! (bonk)', 'Cume! …como eu desço?', 'A pata venceu. O mel é meu!', 'Venci, e barato! (orelhas enroladas)', 'Minha identidade… é segredo. (capuz cai)'],
  },
}

const BOARDS_EN = { search: 'Search', document: 'Documents', i2webdev: 'Image→Web', t2i: 'Text→Image', iedit: 'Image Edit', t2v: 'Text→Video', i2v: 'Image→Video', vedit: 'Video Edit' }
const U: Record<string, V5Ui> = {
  'zh-CN': { vendor: '厂商', model: '型号', search: '搜索型号…', sort: '排序', sortComp: '综合分', sortName: '名称', sortNew: '新人优先', boardsN: '{n} 个榜单', fewData: '数据较少', newcomer: '新人', comp: '综合', noCommon: '这两个型号没有共同参加的榜单，换一个试试。', loading: '加载中…', models: '{n} 个型号', super: '必杀！', parry: '弹反！', block: '格挡！', crit: '暴击！', counter: '反击！', guardBreak: '破防！', finish: '终结！', winner: '胜利！', round: '第{n}回合', other: '其他', openFull: '进入竞技场 →', live: '今日擂台 · 实时演出', boards: { search: '搜索', document: '文档', i2webdev: '图转网页', t2i: '文生图', iedit: '图像编辑', t2v: '文生视频', i2v: '图生视频', vedit: '视频编辑' } },
  'zh-TW': { vendor: '廠商', model: '型號', search: '搜尋型號…', sort: '排序', sortComp: '綜合分', sortName: '名稱', sortNew: '新人優先', boardsN: '{n} 個榜單', fewData: '資料較少', newcomer: '新人', comp: '綜合', noCommon: '這兩個型號沒有共同參加的榜單，換一個試試。', loading: '載入中…', models: '{n} 個型號', super: '必殺！', parry: '彈反！', block: '格擋！', crit: '暴擊！', counter: '反擊！', guardBreak: '破防！', finish: '終結！', winner: '勝利！', round: '第{n}回合', other: '其他', openFull: '進入競技場 →', live: '今日擂台 · 即時演出', boards: { search: '搜尋', document: '文件', i2webdev: '圖轉網頁', t2i: '文生圖', iedit: '影像編輯', t2v: '文生影片', i2v: '圖生影片', vedit: '影片編輯' } },
  en: { vendor: 'Lab', model: 'Model', search: 'Search models…', sort: 'Sort', sortComp: 'Composite', sortName: 'Name', sortNew: 'Newcomers first', boardsN: '{n} boards', fewData: 'Limited data', newcomer: 'NEW', comp: 'Composite', noCommon: 'These two models share no leaderboard. Try another pick.', loading: 'Loading…', models: '{n} models', super: 'SUPER!', parry: 'PARRY!', block: 'BLOCK!', crit: 'CRITICAL!', counter: 'COUNTER!', guardBreak: 'GUARD BREAK!', finish: 'FINISH!', winner: 'WINNER!', round: 'ROUND {n}', other: 'Other', openFull: 'Open the Arena →', live: 'Today’s match · live', boards: BOARDS_EN },
  ja: { vendor: '開発元', model: 'モデル', search: 'モデルを検索…', sort: '並び順', sortComp: '総合スコア', sortName: '名前', sortNew: '新人優先', boardsN: '{n} 個のランキング', fewData: 'データ少なめ', newcomer: '新人', comp: '総合', noCommon: 'この2モデルに共通のランキングがありません。別の組み合わせを試してください。', loading: '読み込み中…', models: '{n} モデル', super: '必殺！', parry: 'パリィ！', block: 'ガード！', crit: 'クリティカル！', counter: 'カウンター！', guardBreak: 'ガードブレイク！', finish: 'フィニッシュ！', winner: '勝利！', round: '第{n}ラウンド', other: 'その他', openFull: 'アリーナへ →', live: '本日の対戦 · ライブ', boards: { search: '検索', document: 'ドキュメント', i2webdev: '画像→Web', t2i: '画像生成', iedit: '画像編集', t2v: '動画生成', i2v: '画像→動画', vedit: '動画編集' } },
  ko: { vendor: '개발사', model: '모델', search: '모델 검색…', sort: '정렬', sortComp: '종합 점수', sortName: '이름', sortNew: '신인 우선', boardsN: '리더보드 {n}개', fewData: '데이터 적음', newcomer: '신인', comp: '종합', noCommon: '두 모델이 함께 오른 리더보드가 없습니다. 다른 조합을 골라 보세요.', loading: '불러오는 중…', models: '모델 {n}개', super: '필살!', parry: '패리!', block: '가드!', crit: '크리티컬!', counter: '카운터!', guardBreak: '가드 브레이크!', finish: '피니시!', winner: '승리!', round: '{n}라운드', other: '기타', openFull: '아레나 입장 →', live: '오늘의 대결 · 라이브', boards: { search: '검색', document: '문서', i2webdev: '이미지→웹', t2i: '이미지 생성', iedit: '이미지 편집', t2v: '영상 생성', i2v: '이미지→영상', vedit: '영상 편집' } },
  fr: { vendor: 'Labo', model: 'Modèle', search: 'Chercher un modèle…', sort: 'Tri', sortComp: 'Score composite', sortName: 'Nom', sortNew: 'Nouveaux d’abord', boardsN: '{n} classements', fewData: 'Peu de données', newcomer: 'NOUVEAU', comp: 'Composite', noCommon: 'Ces deux modèles n’ont aucun classement en commun. Essayez un autre choix.', loading: 'Chargement…', models: '{n} modèles', super: 'SUPER !', parry: 'PARADE !', block: 'BLOCAGE !', crit: 'CRITIQUE !', counter: 'CONTRE !', guardBreak: 'GARDE BRISÉE !', finish: 'FINAL !', winner: 'VICTOIRE !', round: 'ROUND {n}', other: 'Autre', openFull: 'Ouvrir l’Arène →', live: 'Match du jour · en direct', boards: { search: 'Recherche', document: 'Documents', i2webdev: 'Image→Web', t2i: 'Texte→Image', iedit: 'Retouche', t2v: 'Texte→Vidéo', i2v: 'Image→Vidéo', vedit: 'Montage vidéo' } },
  de: { vendor: 'Labor', model: 'Modell', search: 'Modell suchen…', sort: 'Sortierung', sortComp: 'Gesamtwert', sortName: 'Name', sortNew: 'Neulinge zuerst', boardsN: '{n} Ranglisten', fewData: 'Wenig Daten', newcomer: 'NEU', comp: 'Gesamt', noCommon: 'Diese beiden Modelle teilen keine Rangliste. Bitte anders wählen.', loading: 'Lädt…', models: '{n} Modelle', super: 'SUPER!', parry: 'PARADE!', block: 'BLOCK!', crit: 'KRITISCH!', counter: 'KONTER!', guardBreak: 'DECKUNG WEG!', finish: 'FINISH!', winner: 'SIEG!', round: 'RUNDE {n}', other: 'Andere', openFull: 'Zur Arena →', live: 'Kampf des Tages · live', boards: { search: 'Suche', document: 'Dokumente', i2webdev: 'Bild→Web', t2i: 'Text→Bild', iedit: 'Bildbearbeitung', t2v: 'Text→Video', i2v: 'Bild→Video', vedit: 'Videoschnitt' } },
  es: { vendor: 'Laboratorio', model: 'Modelo', search: 'Buscar modelo…', sort: 'Orden', sortComp: 'Puntuación global', sortName: 'Nombre', sortNew: 'Novatos primero', boardsN: '{n} clasificaciones', fewData: 'Pocos datos', newcomer: 'NUEVO', comp: 'Global', noCommon: 'Estos dos modelos no comparten clasificación. Prueba otra pareja.', loading: 'Cargando…', models: '{n} modelos', super: '¡SÚPER!', parry: '¡DESVÍO!', block: '¡BLOQUEO!', crit: '¡CRÍTICO!', counter: '¡CONTRA!', guardBreak: '¡GUARDIA ROTA!', finish: '¡REMATE!', winner: '¡VICTORIA!', round: 'RONDA {n}', other: 'Otros', openFull: 'Abrir la Arena →', live: 'Duelo del día · en vivo', boards: { search: 'Búsqueda', document: 'Documentos', i2webdev: 'Imagen→Web', t2i: 'Texto→Imagen', iedit: 'Edición de imagen', t2v: 'Texto→Vídeo', i2v: 'Imagen→Vídeo', vedit: 'Edición de vídeo' } },
  hi: { vendor: 'लैब', model: 'मॉडल', search: 'मॉडल खोजें…', sort: 'क्रम', sortComp: 'समग्र स्कोर', sortName: 'नाम', sortNew: 'नए पहले', boardsN: '{n} लीडरबोर्ड', fewData: 'कम डेटा', newcomer: 'नया', comp: 'समग्र', noCommon: 'इन दोनों मॉडलों का कोई साझा लीडरबोर्ड नहीं है। दूसरा चुनें।', loading: 'लोड हो रहा है…', models: '{n} मॉडल', super: 'सुपर!', parry: 'पैरी!', block: 'ब्लॉक!', crit: 'क्रिटिकल!', counter: 'काउंटर!', guardBreak: 'गार्ड टूटा!', finish: 'फ़िनिश!', winner: 'विजेता!', round: 'राउंड {n}', other: 'अन्य', openFull: 'अखाड़े में जाएँ →', live: 'आज का मुक़ाबला · लाइव', boards: { search: 'सर्च', document: 'दस्तावेज़', i2webdev: 'इमेज→वेब', t2i: 'टेक्स्ट→इमेज', iedit: 'इमेज एडिट', t2v: 'टेक्स्ट→वीडियो', i2v: 'इमेज→वीडियो', vedit: 'वीडियो एडिट' } },
  th: { vendor: 'ค่าย', model: 'รุ่น', search: 'ค้นหารุ่น…', sort: 'เรียง', sortComp: 'คะแนนรวม', sortName: 'ชื่อ', sortNew: 'น้องใหม่ก่อน', boardsN: '{n} กระดาน', fewData: 'ข้อมูลน้อย', newcomer: 'ใหม่', comp: 'รวม', noCommon: 'สองรุ่นนี้ไม่มีกระดานร่วมกัน ลองเลือกคู่อื่น', loading: 'กำลังโหลด…', models: '{n} รุ่น', super: 'ท่าไม้ตาย!', parry: 'ปัด!', block: 'กัน!', crit: 'คริติคอล!', counter: 'สวนกลับ!', guardBreak: 'ทะลวงการ์ด!', finish: 'ปิดฉาก!', winner: 'ชนะ!', round: 'ยกที่ {n}', other: 'อื่นๆ', openFull: 'เข้าสู่สังเวียน →', live: 'คู่วันนี้ · สด', boards: { search: 'ค้นหา', document: 'เอกสาร', i2webdev: 'ภาพ→เว็บ', t2i: 'ข้อความ→ภาพ', iedit: 'แก้ภาพ', t2v: 'ข้อความ→วิดีโอ', i2v: 'ภาพ→วิดีโอ', vedit: 'ตัดต่อวิดีโอ' } },
  ru: { vendor: 'Лаборатория', model: 'Модель', search: 'Поиск модели…', sort: 'Сортировка', sortComp: 'Общий балл', sortName: 'Название', sortNew: 'Сначала новички', boardsN: 'рейтингов: {n}', fewData: 'Мало данных', newcomer: 'НОВИЧОК', comp: 'Общий', noCommon: 'У этих моделей нет общих рейтингов. Выберите другую пару.', loading: 'Загрузка…', models: 'моделей: {n}', super: 'СУПЕР!', parry: 'ПАРИРОВАНИЕ!', block: 'БЛОК!', crit: 'КРИТ!', counter: 'КОНТРУДАР!', guardBreak: 'ЗАЩИТА ПРОБИТА!', finish: 'ДОБИВАНИЕ!', winner: 'ПОБЕДА!', round: 'РАУНД {n}', other: 'Другие', openFull: 'В арену →', live: 'Бой дня · в эфире', boards: { search: 'Поиск', document: 'Документы', i2webdev: 'Картинка→сайт', t2i: 'Текст→картинка', iedit: 'Правка картинок', t2v: 'Текст→видео', i2v: 'Картинка→видео', vedit: 'Монтаж видео' } },
  pt: { vendor: 'Laboratório', model: 'Modelo', search: 'Buscar modelo…', sort: 'Ordem', sortComp: 'Nota geral', sortName: 'Nome', sortNew: 'Novatos primeiro', boardsN: '{n} rankings', fewData: 'Poucos dados', newcomer: 'NOVO', comp: 'Geral', noCommon: 'Esses dois modelos não dividem nenhum ranking. Tente outra dupla.', loading: 'Carregando…', models: '{n} modelos', super: 'SUPER!', parry: 'APARADA!', block: 'BLOQUEIO!', crit: 'CRÍTICO!', counter: 'CONTRA-ATAQUE!', guardBreak: 'GUARDA QUEBRADA!', finish: 'FINALIZAÇÃO!', winner: 'VITÓRIA!', round: 'ROUND {n}', other: 'Outros', openFull: 'Abrir a Arena →', live: 'Luta do dia · ao vivo', boards: { search: 'Busca', document: 'Documentos', i2webdev: 'Imagem→Web', t2i: 'Texto→Imagem', iedit: 'Edição de imagem', t2v: 'Texto→Vídeo', i2v: 'Imagem→Vídeo', vedit: 'Edição de vídeo' } },
}

export function v5Ui(locale: Locale | string): V5Ui {
  return U[locale] ?? U.en
}
export function v5Lines(locale: Locale | string): { chars: Record<NA, string>; moves: Record<NA, string>; intro: Record<NA, string>; win: Record<NA, string> } {
  const p = P[locale] ?? P.en
  const r = (a: string[]) => Object.fromEntries(NEW_AVATARS.map((k, i) => [k, a[i]])) as Record<NA, string>
  return { chars: r(p.chars), moves: r(p.moves), intro: r(p.intro), win: r(p.win) }
}
